{
    "tarefas": [
        {
          "id": "40151914192203776",
          "idExterno": null,
          "data": "2018-01-02",
          "dataAgendada": "2018-01-02",
          "dataEfetivacao": null,
          "horario": null,
          "situacao": "ABERTO",
          "dataProcessamento": null,
          "custo": null,
          "dataPromessa": null,
          "instrucao": null,
          "contratoParcelaId": null,
          "acao": {
            "id": "38702487301681152",
            "nome": "Ligação",
            "cor": "#001571",
            "custo": "0.20",
            "tipo": "CONTATO",
            "situacao": "ATIVO",
            "api": true,
            "manual": true,
            "gatilho": false,
            "obrigarAgente": false,
            "aprovacao": null,
            "controle": null,
            "horaInicial": null,
            "horaFinal": null,
            "tempo": null,
            "intervalo": null,
            "versao": "2",
            "participantes": null,
            "acaoEmail": null,
            "acaoSerasa": null,
            "acaoSms": null,
            "nomeArquivo": null,
            "assessorias": null
          },
          "agrupador": {
            "id": "38702488007372801",
            "idExterno": "8",
            "dataHoraCriacao": "2017-10-30T19:33:37.000",
            "dataHoraModificacao": "2017-10-30T19:33:37.000",
            "jobInstanceId": "38702487819153408",
            "nome": "Agrupador 8",
            "endereco": null,
            "bairro": null,
            "cidade": null,
            "uf": null,
            "cep": null,
            "telefone": null,
            "email": null,
            "representante": null,
            "situacao": "ATIVO",
            "percentualMulta": "5.0000",
            "percentualMora": "1.5000",
            "metodoAte30": "LINEAR",
            "metodoMais30": "CAPITALIZADO",
            "agentes": null
          },
          "cliente": {
            "id": "38702489929412608",
            "idExterno": "fLPmeJdWioBuouawXBhajLvpdmENNyDLgLacJUFW",
            "dataHoraCriacao": "2017-10-30T19:33:44.000",
            "dataHoraModificacao": "2017-10-30T19:33:45.000",
            "jobInstanceId": "38702489625325568",
            "tipoPessoa": "JURIDICA",
            "nome": "Cliente 167",
            "cic": "59224684000158",
            "codigo": "167",
            "dataNascimento": "1995-10-30",
            "dataConta": "2008-10-30",
            "observacao": null,
            "rg": null,
            "rgUf": null,
            "naturalidade": "bMTsM5CcljK8joXbpukY",
            "naturalidadeUf": "RS",
            "sexo": null,
            "estadoCivil": null,
            "rating": "F",
            "lp": true,
            "situacao": "ATIVO",
            "cicValido": true,
            "medalha": "BRONZE",
            "propensaoPagamento": "MEDIA",
            "historicoPagamento": "4877.00",
            "numeroDiasMaiorAtraso": "0",
            "dataMaiorAtraso": null,
            "rendaTitular": "6264.00",
            "rendaConjuge": "4495.00",
            "outrasRendas": null,
            "profissao": "Nutricionista",
            "categoriaProfissao": "Liberal",
            "tipoResidencia": "Própria",
            "collector": "C",
            "saldoProvisao": null,
            "supervisor": "Supervisor 167",
            "cliente": true,
            "pagador": false,
            "participante": false,
            "agrupador": {
              "id": "38702488007372801",
              "idExterno": "8",
              "dataHoraCriacao": "2017-10-30T19:33:37.000",
              "dataHoraModificacao": "2017-10-30T19:33:37.000",
              "jobInstanceId": "38702487819153408",
              "nome": "Agrupador 8",
              "endereco": null,
              "bairro": null,
              "cidade": null,
              "uf": null,
              "cep": null,
              "telefone": null,
              "email": null,
              "representante": null,
              "situacao": "ATIVO",
              "percentualMulta": "5.0000",
              "percentualMora": "1.5000",
              "metodoAte30": "LINEAR",
              "metodoMais30": "CAPITALIZADO",
              "agentes": null
            },
            "gatilho": null,
            "acordo": false,
            "promessa": false,
            "seguro": true,
            "saldoTotal": "2354.09",
            "saldoTotalMedio": "181.08",
            "saldoContabil": "540.00",
            "valorTotalGarantiasResidual": "0.00",
            "numeroParcelasAberto": "13",
            "diasAtraso": "-25",
            "saldoVencido": "0.00",
            "saldoAtual": "2225.95",
            "saldoAtraso": "0.00",
            "assessorias": null,
            "cartoes": null,
            "emails": null,
            "enderecos": null,
            "telefones": null,
            "referencias": null,
            "limites": null,
            "grupos": null,
            "socios": null,
            "observacoes": null,
            "marcadores": null,
            "informacoesAdicionais": null,
            "loteCartaRegistros": null
          },
          "acordoParcela": null,
          "assessoria": null,
          "workflow": null,
          "instancia": null,
          "instanciaElemento": null,
          "usuario": null,
          "motivoContato": null,
          "usuarioAgendador": {
            "id": "38702486766383104",
            "idExterno": "test01",
            "dataHoraCriacao": "2017-10-30T19:33:32.000",
            "dataHoraModificacao": "2018-01-03T20:48:32.000",
            "jobInstanceId": null,
            "codigo": "test01",
            "nome": "test01",
            "situacao": "ATIVO",
            "tipo": "USUARIO",
            "dataUltAcesso": "2018-01-26T18:52:58.000",
            "numeroTentativaAcesso": "0",
            "dataHoraTentativa": null,
            "bloqueado": false,
            "cpf": "55629165500",
            "email": "test01@tivea.com.br",
            "criptografia": "MD5",
            "admin": false,
            "ramal": null,
            "paginacaoPadrao": null,
            "notificacaoTarefa": null,
            "assessoria": null,
            "perfil": {
              "id": "38702486764285952"
            },
            "autorizacoes": null,
            "agrupadores": [
              {
                "id": "38702488007372801",
                "idExterno": "8",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 8",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007110659",
                "idExterno": "5",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 5",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007110658",
                "idExterno": "4",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 4",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488006848512",
                "idExterno": "1",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 1",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007110660",
                "idExterno": "6",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 6",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007634944",
                "idExterno": "10",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 10",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007372802",
                "idExterno": "9",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 9",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007110656",
                "idExterno": "2",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 2",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007110657",
                "idExterno": "3",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 3",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              },
              {
                "id": "38702488007372800",
                "idExterno": "7",
                "dataHoraCriacao": "2017-10-30T19:33:37.000",
                "dataHoraModificacao": "2017-10-30T19:33:37.000",
                "jobInstanceId": "38702487819153408",
                "nome": "Agrupador 7",
                "endereco": null,
                "bairro": null,
                "cidade": null,
                "uf": null,
                "cep": null,
                "telefone": null,
                "email": null,
                "representante": null,
                "situacao": "ATIVO",
                "percentualMulta": "5.0000",
                "percentualMora": "1.5000",
                "metodoAte30": "LINEAR",
                "metodoMais30": "CAPITALIZADO",
                "agentes": null
              }
            ]
          },
          "documentos": [],
          "observacoes": null,
          "contratos": null
        }
      ]
}